# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js image for building the application
FROM node:20 AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json for dependency installation
COPY package.json package.json

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application using TypeScript
RUN npm run build

# Use a lighter Node.js image for the final stage
FROM node:20-slim

# Set the working directory
WORKDIR /app

# Copy the build files from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/node_modules /app/node_modules

# Define environment variables (these can be overridden during runtime)
ENV GIT_DEFAULT_PATH=/path/to/default/git/directory
ENV GITHUB_PERSONAL_ACCESS_TOKEN=your-github-pat

# Set the entrypoint command
ENTRYPOINT ["node", "build/index.js"]
